server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
        native:
          search-locations: ${LOCAL_REPOSITORY:C:/Users/WINDOWS/Desktop/self-study/paymentchain-bank-project/config-server-repo}
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
