user:
    role: carlosbrrs
    alias: carlosbrrs
spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    datasource:
        url: jdbc:postgresql://192.168.10.120:5432/springboot
        username: amdin
        password: admin