user:
    role: developer
    alias: carlosbrrs
spring:
    jpa:
        show-sql: true
    datasource:
        url: jdbc:h2:mem:customer-ms-db
        username: sa
        password:
        driverClassName: org.h2.Driver